#' Generate an attenuated sequence
#'
#' @description
#' Generates a sequence of values starting from an initial value,
#' with a given velocity that is attenuated over time.
#'
#' For `bounce_off()`, a sequence is constrained
#' so that the values never go outside of a given range.
#' The sequence is generated by applying a damping factor
#' to the velocity when it exceeds `limits`.
#'
#' @param n An integer scalar. The number of steps in the sequence.
#' @param init A numeric scalar. The initial value of the sequence.
#' @param velocity A numeric scalar. The velocity or change rate for each step.
#' @param limits A numeric vector of length 2. The minimum and maximum values allowed in the sequence.
#' @param damping A numeric scalar. The damping factor applied to the velocity at each step.
#' @returns A numeric vector.
#' @rdname attenuate
#' @name attenuate
NULL

#' @rdname attenuate
#' @export
attenuate <- function(n, init, velocity, damping = 1) {
  if (damping <= 0) {
    rlang::warn("Damping factor must be non-negative")
  }
  sq <- seq_len(n)
  c(init, init + cumsum(velocity * damping^sq))
}

#' @rdname attenuate
#' @export
bounce_off <- function(n, init, velocity, limits, damping = -1) {
  if (damping >= 0) {
    rlang::warn("Damping factor must be negative")
  }
  limits <- as.double(limits)
  bounce_cpp(
    as.integer(n),
    as.double(init),
    as.double(velocity),
    as.double(damping),
    limits[1],
    limits[2]
  )
}
