# Generated by cpp11: do not edit by hand

bounce_cpp <- function(n, init, velocity, damping, mass, min, max) {
  .Call(`_rasengan_bounce_cpp`, n, init, velocity, damping, mass, min, max)
}

in_quad <- function(time) {
  .Call(`_rasengan_in_quad`, time)
}

out_quad <- function(time) {
  .Call(`_rasengan_out_quad`, time)
}

in_out_quad <- function(time) {
  .Call(`_rasengan_in_out_quad`, time)
}

in_cubic <- function(time) {
  .Call(`_rasengan_in_cubic`, time)
}

out_cubic <- function(time) {
  .Call(`_rasengan_out_cubic`, time)
}

in_out_cubic <- function(time) {
  .Call(`_rasengan_in_out_cubic`, time)
}

in_quart <- function(time) {
  .Call(`_rasengan_in_quart`, time)
}

out_quart <- function(time) {
  .Call(`_rasengan_out_quart`, time)
}

in_out_quart <- function(time) {
  .Call(`_rasengan_in_out_quart`, time)
}

in_quint <- function(time) {
  .Call(`_rasengan_in_quint`, time)
}

out_quint <- function(time) {
  .Call(`_rasengan_out_quint`, time)
}

in_out_quint <- function(time) {
  .Call(`_rasengan_in_out_quint`, time)
}

in_sine <- function(time) {
  .Call(`_rasengan_in_sine`, time)
}

out_sine <- function(time) {
  .Call(`_rasengan_out_sine`, time)
}

in_out_sine <- function(time) {
  .Call(`_rasengan_in_out_sine`, time)
}

in_exp <- function(time) {
  .Call(`_rasengan_in_exp`, time)
}

out_exp <- function(time) {
  .Call(`_rasengan_out_exp`, time)
}

in_out_exp <- function(time) {
  .Call(`_rasengan_in_out_exp`, time)
}

in_circ <- function(time) {
  .Call(`_rasengan_in_circ`, time)
}

out_circ <- function(time) {
  .Call(`_rasengan_out_circ`, time)
}

in_out_circ <- function(time) {
  .Call(`_rasengan_in_out_circ`, time)
}

in_elastic <- function(time) {
  .Call(`_rasengan_in_elastic`, time)
}

out_elastic <- function(time) {
  .Call(`_rasengan_out_elastic`, time)
}

in_out_elastic <- function(time) {
  .Call(`_rasengan_in_out_elastic`, time)
}

in_back <- function(time) {
  .Call(`_rasengan_in_back`, time)
}

out_back <- function(time) {
  .Call(`_rasengan_out_back`, time)
}

in_out_back <- function(time) {
  .Call(`_rasengan_in_out_back`, time)
}

in_bounce <- function(time) {
  .Call(`_rasengan_in_bounce`, time)
}

out_bounce <- function(time) {
  .Call(`_rasengan_out_bounce`, time)
}

in_out_bounce <- function(time) {
  .Call(`_rasengan_in_out_bounce`, time)
}

fbm_1d_cpp <- function(hurst_idx, X) {
  .Call(`_rasengan_fbm_1d_cpp`, hurst_idx, X)
}

fbr_1d_cpp <- function(hurst_idx, X) {
  .Call(`_rasengan_fbr_1d_cpp`, hurst_idx, X)
}

fbr_2d_cpp <- function(hurst_idx, X) {
  .Call(`_rasengan_fbr_2d_cpp`, hurst_idx, X)
}

noise_2d_cpp <- function(type, seed, freq, fractals, octaves, lacunarity, gain, weighted_strength, ping_pong_strength, distance_function, return_type, jitter, d) {
  .Call(`_rasengan_noise_2d_cpp`, type, seed, freq, fractals, octaves, lacunarity, gain, weighted_strength, ping_pong_strength, distance_function, return_type, jitter, d)
}

noise_3d_cpp <- function(type, seed, freq, fractals, octaves, lacunarity, gain, weighted_strength, ping_pong_strength, distance_function, return_type, jitter, rotation_type, d) {
  .Call(`_rasengan_noise_3d_cpp`, type, seed, freq, fractals, octaves, lacunarity, gain, weighted_strength, ping_pong_strength, distance_function, return_type, jitter, rotation_type, d)
}

domain_warp_2d_cpp <- function(dtype, seed, amplitude, fractals, octaves, lacunarity, gain, d) {
  .Call(`_rasengan_domain_warp_2d_cpp`, dtype, seed, amplitude, fractals, octaves, lacunarity, gain, d)
}

domain_warp_3d_cpp <- function(dtype, seed, amplitude, fractals, octaves, lacunarity, gain, rotation_type, d) {
  .Call(`_rasengan_domain_warp_3d_cpp`, dtype, seed, amplitude, fractals, octaves, lacunarity, gain, rotation_type, d)
}

es_spiral_cpp <- function(start, end, num_iter, max_n) {
  .Call(`_rasengan_es_spiral_cpp`, start, end, num_iter, max_n)
}

es_biarc_cpp <- function(start, end, max_n) {
  .Call(`_rasengan_es_biarc_cpp`, start, end, max_n)
}

wind_mouse_cpp <- function(start, end, gravity, wind, min_wait, max_wait, max_step, target_area, mouse_speed, seed) {
  .Call(`_rasengan_wind_mouse_cpp`, start, end, gravity, wind, min_wait, max_wait, max_step, target_area, mouse_speed, seed)
}

genidx_rings_cpp <- function(mat) {
  .Call(`_rasengan_genidx_rings_cpp`, mat)
}

genidx_spiral_cpp <- function(mat) {
  .Call(`_rasengan_genidx_spiral_cpp`, mat)
}

genidx_stride_cpp <- function(n, step) {
  .Call(`_rasengan_genidx_stride_cpp`, n, step)
}

genidx_zigzag_cpp <- function(mat) {
  .Call(`_rasengan_genidx_zigzag_cpp`, mat)
}
