# Generated by cpp11: do not edit by hand

es_spiral_cpp <- function(start, end, num_iter, max_n) {
  .Call(`_rasengan_es_spiral_cpp`, start, end, num_iter, max_n)
}

es_biarc_cpp <- function(start, end, max_n) {
  .Call(`_rasengan_es_biarc_cpp`, start, end, max_n)
}

wind_mouse_cpp <- function(start, end, gravity, wind, min_wait, max_wait, max_step, target_area, mouse_speed, seed) {
  .Call(`_rasengan_wind_mouse_cpp`, start, end, gravity, wind, min_wait, max_wait, max_step, target_area, mouse_speed, seed)
}
