# Generated by cpp11: do not edit by hand

wind_mouse_cpp <- function(start, end, gravity, wind, min_wait, max_wait, max_step, target_area, mouse_speed, seed) {
  .Call(`_rasengan_wind_mouse_cpp`, start, end, gravity, wind, min_wait, max_wait, max_step, target_area, mouse_speed, seed)
}
