loess <- function(x, span, ...) {
  d <- data.frame(t = stats::time(x), w = x)
  stats::loess(w ~ t, d, span = span, ...)
}

#' Generate a random curve
#'
#' Generates a random smooth curve using fractional Brownian bridges.
#' This function fits a series of points that are generated by [fbbridge_from()]
#' using [stats::loess()] and returns predicted points for `n` time steps.
#'
#' @param n An integer scalar. The number of points to generate.
#' @param smoothing An numeric scalar.
#'  Smoothing parameter to be passed to [stats::loess()] as `span`.
#' @param ... Additional arguments to be passed to [stats::loess()].
#' @inheritParams fbbridge_from
#' @returns A data frame with columns `x` and `y`.
#' @family curve
#' @export
curve_random <- function(
  n,
  power = 8,
  hurst_index = 0.5,
  smoothing = 0.4,
  ...
) {
  x_base <- fbbridge_from(power, hurst_index)(stats::runif)
  y_base <- fbbridge_from(power, hurst_index)(stats::runif)
  dat <- data.frame(t = seq_len(n) / power)
  ret <- data.frame(
    x = unname(predict(loess(x_base, span = smoothing, ...), dat)),
    y = unname(predict(loess(y_base, span = smoothing, ...), dat))
  )
  entbl(ret)
}
